title: Kristoffer's Portfolio
email: peiwebdev@gmail.com
url: peidev.top
description: > # this means to ignore newlines until "baseurl:"
  Kristoffer's portfolio. A collection of new knowledge in web development.
author: Kristofferson Carillo
# Build settings
markdown: kramdown
plugins:
  - jekyll-feed