
# Admin Information
title: Kristofferson Carillo
position: Web Developer
author: Kristofferson Carillo
profile: "kristofferson-carillo.png"
email: peiwebdev@gmail.com
github_username:  jekyll
twitter:
  username: peisop

github_username:  jekyll
# Site Information
url: "http://peidev.top"
baseurl: "" 
lang: english
description: >-
  I build great websites and automation tools with wordpress and python. I also enjoy writing content for my blog and finding ways to earn online. Follow me on Twitter or drop a line.

# Build settings
livereload: true
markdown: kramdown
highlighter: rouge

sass: 
 # style: compressed
plugins:
  - jekyll-feed
  - jekyll-livereload
  - jekyll-seo-tag
  - jemoji
kramdown:
  input: GFM
  syntax_highlighter: rouge


# Exclude from processing.
exclude:
    - node_modules
    - package.json


# Paths
img_path: '/assets/static'